# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Robot/MastersSafeKeeping/full_design/full_design.srcs/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/design_1_FFT_IP_1_0.xci
# IP: The module: 'design_1_FFT_IP_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robot/MastersSafeKeeping/full_design/full_design.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/constraints/FFT_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FFT_IP_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Robot/MastersSafeKeeping/full_design/full_design.srcs/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/design_1_FFT_IP_1_0.xci
# IP: The module: 'design_1_FFT_IP_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robot/MastersSafeKeeping/full_design/full_design.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/constraints/FFT_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FFT_IP_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
