// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FFT_IP_transform (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        f_0_address0,
        f_0_ce0,
        f_0_we0,
        f_0_d0,
        f_0_q0,
        f_0_address1,
        f_0_ce1,
        f_0_q1,
        f_1_address0,
        f_1_ce0,
        f_1_we0,
        f_1_d0,
        f_1_q0,
        f_1_address1,
        f_1_ce1,
        f_1_q1,
        grp_fu_124_p_din0,
        grp_fu_124_p_din1,
        grp_fu_124_p_opcode,
        grp_fu_124_p_dout0,
        grp_fu_124_p_ce,
        grp_fu_128_p_din0,
        grp_fu_128_p_din1,
        grp_fu_128_p_dout0,
        grp_fu_128_p_ce,
        grp_fu_132_p_din0,
        grp_fu_132_p_din1,
        grp_fu_132_p_dout0,
        grp_fu_132_p_ce
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] f_0_address0;
output   f_0_ce0;
output   f_0_we0;
output  [31:0] f_0_d0;
input  [31:0] f_0_q0;
output  [12:0] f_0_address1;
output   f_0_ce1;
input  [31:0] f_0_q1;
output  [12:0] f_1_address0;
output   f_1_ce0;
output   f_1_we0;
output  [31:0] f_1_d0;
input  [31:0] f_1_q0;
output  [12:0] f_1_address1;
output   f_1_ce1;
input  [31:0] f_1_q1;
output  [31:0] grp_fu_124_p_din0;
output  [31:0] grp_fu_124_p_din1;
output  [1:0] grp_fu_124_p_opcode;
input  [31:0] grp_fu_124_p_dout0;
output   grp_fu_124_p_ce;
output  [31:0] grp_fu_128_p_din0;
output  [31:0] grp_fu_128_p_din1;
input  [31:0] grp_fu_128_p_dout0;
output   grp_fu_128_p_ce;
output  [31:0] grp_fu_132_p_din0;
output  [31:0] grp_fu_132_p_din1;
input  [31:0] grp_fu_132_p_dout0;
output   grp_fu_132_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] f_0_address0;
reg f_0_ce0;
reg f_0_we0;
reg[31:0] f_0_d0;
reg f_0_ce1;
reg[12:0] f_1_address0;
reg f_1_ce0;
reg f_1_we0;
reg[31:0] f_1_d0;
reg f_1_ce1;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] this_M_value_13_reg_400;
wire   [12:0] this_M_value_14_reg_406;
wire   [63:0] grp_sin_or_cos_double_s_fu_227_ap_return;
reg   [63:0] tmp_reg_412;
wire    ap_CS_fsm_state3;
wire   [63:0] grp_sin_or_cos_double_s_fu_243_ap_return;
reg   [63:0] tmp_1_reg_417;
wire   [31:0] grp_fu_302_p1;
reg   [31:0] conv_i_reg_422;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_305_p1;
reg   [31:0] conv3_i_reg_427;
reg   [12:0] i_1_reg_432;
wire    ap_CS_fsm_state8;
wire   [11:0] p_n_fu_333_p1;
reg   [11:0] p_n_reg_442;
wire    ap_CS_fsm_state9;
wire   [31:0] W_M_value_q0;
reg   [31:0] p_x_M_value_5_reg_447;
wire   [31:0] W_M_value_1_q0;
reg   [31:0] p_x_M_value_reg_452;
wire   [31:0] p_x_M_value_8_fu_340_p3;
reg   [31:0] p_x_M_value_8_reg_457;
wire   [31:0] p_x_M_value_9_fu_349_p3;
reg   [31:0] p_x_M_value_9_reg_462;
reg   [12:0] f2_M_value_address0;
reg    f2_M_value_ce0;
reg    f2_M_value_we0;
reg   [31:0] f2_M_value_d0;
wire   [31:0] f2_M_value_q0;
wire   [12:0] f2_M_value_address1;
reg    f2_M_value_ce1;
reg    f2_M_value_we1;
reg   [12:0] f2_M_value_1_address0;
reg    f2_M_value_1_ce0;
reg    f2_M_value_1_we0;
reg   [31:0] f2_M_value_1_d0;
wire   [31:0] f2_M_value_1_q0;
wire   [12:0] f2_M_value_1_address1;
reg    f2_M_value_1_ce1;
reg    f2_M_value_1_we1;
reg   [12:0] W_M_value_address0;
reg    W_M_value_ce0;
reg    W_M_value_we0;
reg   [31:0] W_M_value_d0;
reg   [12:0] W_M_value_address1;
reg    W_M_value_ce1;
reg    W_M_value_we1;
reg   [31:0] W_M_value_d1;
reg   [12:0] W_M_value_1_address0;
reg    W_M_value_1_ce0;
reg    W_M_value_1_we0;
reg   [31:0] W_M_value_1_d0;
reg   [12:0] W_M_value_1_address1;
reg    W_M_value_1_ce1;
reg    W_M_value_1_we1;
reg   [31:0] W_M_value_1_d1;
wire    grp_transform_Pipeline_1_fu_215_ap_start;
wire    grp_transform_Pipeline_1_fu_215_ap_done;
wire    grp_transform_Pipeline_1_fu_215_ap_idle;
wire    grp_transform_Pipeline_1_fu_215_ap_ready;
wire   [12:0] grp_transform_Pipeline_1_fu_215_f2_M_value_address0;
wire    grp_transform_Pipeline_1_fu_215_f2_M_value_ce0;
wire    grp_transform_Pipeline_1_fu_215_f2_M_value_we0;
wire   [31:0] grp_transform_Pipeline_1_fu_215_f2_M_value_d0;
wire   [12:0] grp_transform_Pipeline_1_fu_215_f2_M_value_1_address0;
wire    grp_transform_Pipeline_1_fu_215_f2_M_value_1_ce0;
wire    grp_transform_Pipeline_1_fu_215_f2_M_value_1_we0;
wire   [31:0] grp_transform_Pipeline_1_fu_215_f2_M_value_1_d0;
wire    grp_transform_Pipeline_4_fu_221_ap_start;
wire    grp_transform_Pipeline_4_fu_221_ap_done;
wire    grp_transform_Pipeline_4_fu_221_ap_idle;
wire    grp_transform_Pipeline_4_fu_221_ap_ready;
wire   [12:0] grp_transform_Pipeline_4_fu_221_W_M_value_address0;
wire    grp_transform_Pipeline_4_fu_221_W_M_value_ce0;
wire    grp_transform_Pipeline_4_fu_221_W_M_value_we0;
wire   [31:0] grp_transform_Pipeline_4_fu_221_W_M_value_d0;
wire   [12:0] grp_transform_Pipeline_4_fu_221_W_M_value_1_address0;
wire    grp_transform_Pipeline_4_fu_221_W_M_value_1_ce0;
wire    grp_transform_Pipeline_4_fu_221_W_M_value_1_we0;
wire   [31:0] grp_transform_Pipeline_4_fu_221_W_M_value_1_d0;
wire    grp_sin_or_cos_double_s_fu_227_ap_start;
wire    grp_sin_or_cos_double_s_fu_227_ap_done;
wire    grp_sin_or_cos_double_s_fu_227_ap_idle;
wire    grp_sin_or_cos_double_s_fu_227_ap_ready;
wire    grp_sin_or_cos_double_s_fu_227_do_cos;
wire    grp_sin_or_cos_double_s_fu_243_ap_start;
wire    grp_sin_or_cos_double_s_fu_243_ap_done;
wire    grp_sin_or_cos_double_s_fu_243_ap_idle;
wire    grp_sin_or_cos_double_s_fu_243_ap_ready;
wire    grp_sin_or_cos_double_s_fu_243_do_cos;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_idle;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_ready;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_ce0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_ce0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_d0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_d0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_idle;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_ready;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_ce0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_ce0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_d0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_d0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_idle;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_ready;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_d0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce1;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_we0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_d0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce1;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_ce0;
wire   [12:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_address0;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_ce0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din1;
wire   [1:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_opcode;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_ce;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din1;
wire   [1:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_opcode;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_ce;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_ce;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_ce;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_ce;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din0;
wire   [31:0] grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din1;
wire    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_ce;
wire    grp_transform_Pipeline_5_fu_289_ap_start;
wire    grp_transform_Pipeline_5_fu_289_ap_done;
wire    grp_transform_Pipeline_5_fu_289_ap_idle;
wire    grp_transform_Pipeline_5_fu_289_ap_ready;
wire   [31:0] grp_transform_Pipeline_5_fu_289_agg_result_0_0_i_out;
wire    grp_transform_Pipeline_5_fu_289_agg_result_0_0_i_out_ap_vld;
wire   [31:0] grp_transform_Pipeline_5_fu_289_agg_result_1_0_i_out;
wire    grp_transform_Pipeline_5_fu_289_agg_result_1_0_i_out_ap_vld;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din1;
wire   [0:0] grp_transform_Pipeline_5_fu_289_grp_fu_467_p_opcode;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_467_p_ce;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din1;
wire   [0:0] grp_transform_Pipeline_5_fu_289_grp_fu_471_p_opcode;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_471_p_ce;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din1;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_475_p_ce;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din1;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_479_p_ce;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din1;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_483_p_ce;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din0;
wire   [31:0] grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din1;
wire    grp_transform_Pipeline_5_fu_289_grp_fu_487_p_ce;
reg    grp_transform_Pipeline_1_fu_215_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_transform_Pipeline_4_fu_221_ap_start_reg;
reg    grp_sin_or_cos_double_s_fu_227_ap_start_reg;
reg    grp_sin_or_cos_double_s_fu_243_ap_start_reg;
reg    grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg;
wire   [0:0] icmp_ln59_fu_316_p2;
wire    ap_CS_fsm_state12;
reg    grp_transform_Pipeline_5_fu_289_ap_start_reg;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln59_fu_358_p1;
wire    ap_CS_fsm_state11;
reg   [12:0] i_fu_56;
wire   [12:0] add_ln59_fu_322_p2;
wire   [0:0] trunc_ln60_1_fu_337_p1;
reg    grp_fu_302_ce;
reg    grp_fu_305_ce;
reg   [31:0] grp_fu_467_p0;
reg   [31:0] grp_fu_467_p1;
reg   [1:0] grp_fu_467_opcode;
reg    grp_fu_467_ce;
wire   [31:0] grp_fu_471_p2;
reg   [31:0] grp_fu_471_p0;
reg   [31:0] grp_fu_471_p1;
reg   [1:0] grp_fu_471_opcode;
reg    grp_fu_471_ce;
reg   [31:0] grp_fu_475_p0;
reg   [31:0] grp_fu_475_p1;
reg    grp_fu_475_ce;
reg   [31:0] grp_fu_479_p0;
reg   [31:0] grp_fu_479_p1;
reg    grp_fu_479_ce;
wire   [31:0] grp_fu_483_p2;
reg   [31:0] grp_fu_483_p0;
reg   [31:0] grp_fu_483_p1;
reg    grp_fu_483_ce;
wire   [31:0] grp_fu_487_p2;
reg   [31:0] grp_fu_487_p0;
reg   [31:0] grp_fu_487_p1;
reg    grp_fu_487_ce;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_transform_Pipeline_1_fu_215_ap_start_reg = 1'b0;
#0 grp_transform_Pipeline_4_fu_221_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_s_fu_227_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_s_fu_243_ap_start_reg = 1'b0;
#0 grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg = 1'b0;
#0 grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg = 1'b0;
#0 grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg = 1'b0;
#0 grp_transform_Pipeline_5_fu_289_ap_start_reg = 1'b0;
end

FFT_IP_transform_f2_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
f2_M_value_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(f2_M_value_address0),
    .ce0(f2_M_value_ce0),
    .we0(f2_M_value_we0),
    .d0(f2_M_value_d0),
    .q0(f2_M_value_q0),
    .address1(f2_M_value_address1),
    .ce1(f2_M_value_ce1),
    .we1(f2_M_value_we1),
    .d1(32'd0)
);

FFT_IP_transform_f2_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
f2_M_value_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(f2_M_value_1_address0),
    .ce0(f2_M_value_1_ce0),
    .we0(f2_M_value_1_we0),
    .d0(f2_M_value_1_d0),
    .q0(f2_M_value_1_q0),
    .address1(f2_M_value_1_address1),
    .ce1(f2_M_value_1_ce1),
    .we1(f2_M_value_1_we1),
    .d1(32'd0)
);

FFT_IP_transform_f2_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
W_M_value_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_M_value_address0),
    .ce0(W_M_value_ce0),
    .we0(W_M_value_we0),
    .d0(W_M_value_d0),
    .q0(W_M_value_q0),
    .address1(W_M_value_address1),
    .ce1(W_M_value_ce1),
    .we1(W_M_value_we1),
    .d1(W_M_value_d1)
);

FFT_IP_transform_f2_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
W_M_value_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_M_value_1_address0),
    .ce0(W_M_value_1_ce0),
    .we0(W_M_value_1_we0),
    .d0(W_M_value_1_d0),
    .q0(W_M_value_1_q0),
    .address1(W_M_value_1_address1),
    .ce1(W_M_value_1_ce1),
    .we1(W_M_value_1_we1),
    .d1(W_M_value_1_d1)
);

FFT_IP_transform_Pipeline_1 grp_transform_Pipeline_1_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_1_fu_215_ap_start),
    .ap_done(grp_transform_Pipeline_1_fu_215_ap_done),
    .ap_idle(grp_transform_Pipeline_1_fu_215_ap_idle),
    .ap_ready(grp_transform_Pipeline_1_fu_215_ap_ready),
    .f2_M_value_address0(grp_transform_Pipeline_1_fu_215_f2_M_value_address0),
    .f2_M_value_ce0(grp_transform_Pipeline_1_fu_215_f2_M_value_ce0),
    .f2_M_value_we0(grp_transform_Pipeline_1_fu_215_f2_M_value_we0),
    .f2_M_value_d0(grp_transform_Pipeline_1_fu_215_f2_M_value_d0),
    .f2_M_value_1_address0(grp_transform_Pipeline_1_fu_215_f2_M_value_1_address0),
    .f2_M_value_1_ce0(grp_transform_Pipeline_1_fu_215_f2_M_value_1_ce0),
    .f2_M_value_1_we0(grp_transform_Pipeline_1_fu_215_f2_M_value_1_we0),
    .f2_M_value_1_d0(grp_transform_Pipeline_1_fu_215_f2_M_value_1_d0)
);

FFT_IP_transform_Pipeline_4 grp_transform_Pipeline_4_fu_221(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_4_fu_221_ap_start),
    .ap_done(grp_transform_Pipeline_4_fu_221_ap_done),
    .ap_idle(grp_transform_Pipeline_4_fu_221_ap_idle),
    .ap_ready(grp_transform_Pipeline_4_fu_221_ap_ready),
    .W_M_value_address0(grp_transform_Pipeline_4_fu_221_W_M_value_address0),
    .W_M_value_ce0(grp_transform_Pipeline_4_fu_221_W_M_value_ce0),
    .W_M_value_we0(grp_transform_Pipeline_4_fu_221_W_M_value_we0),
    .W_M_value_d0(grp_transform_Pipeline_4_fu_221_W_M_value_d0),
    .W_M_value_1_address0(grp_transform_Pipeline_4_fu_221_W_M_value_1_address0),
    .W_M_value_1_ce0(grp_transform_Pipeline_4_fu_221_W_M_value_1_ce0),
    .W_M_value_1_we0(grp_transform_Pipeline_4_fu_221_W_M_value_1_we0),
    .W_M_value_1_d0(grp_transform_Pipeline_4_fu_221_W_M_value_1_d0)
);

FFT_IP_sin_or_cos_double_s grp_sin_or_cos_double_s_fu_227(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_s_fu_227_ap_start),
    .ap_done(grp_sin_or_cos_double_s_fu_227_ap_done),
    .ap_idle(grp_sin_or_cos_double_s_fu_227_ap_idle),
    .ap_ready(grp_sin_or_cos_double_s_fu_227_ap_ready),
    .do_cos(grp_sin_or_cos_double_s_fu_227_do_cos),
    .ap_return(grp_sin_or_cos_double_s_fu_227_ap_return)
);

FFT_IP_sin_or_cos_double_s grp_sin_or_cos_double_s_fu_243(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_s_fu_243_ap_start),
    .ap_done(grp_sin_or_cos_double_s_fu_243_ap_done),
    .ap_idle(grp_sin_or_cos_double_s_fu_243_ap_idle),
    .ap_ready(grp_sin_or_cos_double_s_fu_243_ap_ready),
    .do_cos(grp_sin_or_cos_double_s_fu_243_do_cos),
    .ap_return(grp_sin_or_cos_double_s_fu_243_ap_return)
);

FFT_IP_transform_Pipeline_VITIS_LOOP_44_1 grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start),
    .ap_done(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done),
    .ap_idle(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_idle),
    .ap_ready(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_ready),
    .f_0_address0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_address0),
    .f_0_ce0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_ce0),
    .f_0_q0(f_0_q0),
    .f_1_address0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_address0),
    .f_1_ce0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_ce0),
    .f_1_q0(f_1_q0),
    .f2_M_value_address0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_address0),
    .f2_M_value_ce0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_ce0),
    .f2_M_value_we0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_we0),
    .f2_M_value_d0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_d0),
    .f2_M_value_1_address0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_address0),
    .f2_M_value_1_ce0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_ce0),
    .f2_M_value_1_we0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_we0),
    .f2_M_value_1_d0(grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_d0)
);

FFT_IP_transform_Pipeline_VITIS_LOOP_47_2 grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start),
    .ap_done(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done),
    .ap_idle(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_idle),
    .ap_ready(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_ready),
    .f2_M_value_address0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_address0),
    .f2_M_value_ce0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_ce0),
    .f2_M_value_q0(f2_M_value_q0),
    .f2_M_value_1_address0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_address0),
    .f2_M_value_1_ce0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_ce0),
    .f2_M_value_1_q0(f2_M_value_1_q0),
    .f_0_address0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_address0),
    .f_0_ce0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_ce0),
    .f_0_we0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_we0),
    .f_0_d0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_d0),
    .f_1_address0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_address0),
    .f_1_ce0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_ce0),
    .f_1_we0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_we0),
    .f_1_d0(grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_d0)
);

FFT_IP_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3 grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start),
    .ap_done(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done),
    .ap_idle(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_idle),
    .ap_ready(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_ready),
    .f_0_address0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address0),
    .f_0_ce0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce0),
    .f_0_we0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_we0),
    .f_0_d0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_d0),
    .f_0_q0(f_0_q0),
    .f_0_address1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address1),
    .f_0_ce1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce1),
    .f_0_q1(f_0_q1),
    .f_1_address0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address0),
    .f_1_ce0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce0),
    .f_1_we0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_we0),
    .f_1_d0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_d0),
    .f_1_q0(f_1_q0),
    .f_1_address1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address1),
    .f_1_ce1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce1),
    .f_1_q1(f_1_q1),
    .W_M_value_address0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_address0),
    .W_M_value_ce0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_ce0),
    .W_M_value_q0(W_M_value_q0),
    .W_M_value_1_address0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_address0),
    .W_M_value_1_ce0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_ce0),
    .W_M_value_1_q0(W_M_value_1_q0),
    .grp_fu_467_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din0),
    .grp_fu_467_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din1),
    .grp_fu_467_p_opcode(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_opcode),
    .grp_fu_467_p_dout0(grp_fu_124_p_dout0),
    .grp_fu_467_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_ce),
    .grp_fu_471_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din0),
    .grp_fu_471_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din1),
    .grp_fu_471_p_opcode(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_opcode),
    .grp_fu_471_p_dout0(grp_fu_471_p2),
    .grp_fu_471_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_ce),
    .grp_fu_475_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din0),
    .grp_fu_475_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din1),
    .grp_fu_475_p_dout0(grp_fu_128_p_dout0),
    .grp_fu_475_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_ce),
    .grp_fu_479_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din0),
    .grp_fu_479_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din1),
    .grp_fu_479_p_dout0(grp_fu_132_p_dout0),
    .grp_fu_479_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_ce),
    .grp_fu_483_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din0),
    .grp_fu_483_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din1),
    .grp_fu_483_p_dout0(grp_fu_483_p2),
    .grp_fu_483_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_ce),
    .grp_fu_487_p_din0(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din0),
    .grp_fu_487_p_din1(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din1),
    .grp_fu_487_p_dout0(grp_fu_487_p2),
    .grp_fu_487_p_ce(grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_ce)
);

FFT_IP_transform_Pipeline_5 grp_transform_Pipeline_5_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transform_Pipeline_5_fu_289_ap_start),
    .ap_done(grp_transform_Pipeline_5_fu_289_ap_done),
    .ap_idle(grp_transform_Pipeline_5_fu_289_ap_idle),
    .ap_ready(grp_transform_Pipeline_5_fu_289_ap_ready),
    .p_x_M_value_9(p_x_M_value_8_reg_457),
    .p_x_M_value_10(p_x_M_value_9_reg_462),
    .p_x_M_value_2(p_x_M_value_5_reg_447),
    .p_x_M_value_1(p_x_M_value_reg_452),
    .p_n(p_n_reg_442),
    .agg_result_0_0_i_out(grp_transform_Pipeline_5_fu_289_agg_result_0_0_i_out),
    .agg_result_0_0_i_out_ap_vld(grp_transform_Pipeline_5_fu_289_agg_result_0_0_i_out_ap_vld),
    .agg_result_1_0_i_out(grp_transform_Pipeline_5_fu_289_agg_result_1_0_i_out),
    .agg_result_1_0_i_out_ap_vld(grp_transform_Pipeline_5_fu_289_agg_result_1_0_i_out_ap_vld),
    .grp_fu_467_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din0),
    .grp_fu_467_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din1),
    .grp_fu_467_p_opcode(grp_transform_Pipeline_5_fu_289_grp_fu_467_p_opcode),
    .grp_fu_467_p_dout0(grp_fu_124_p_dout0),
    .grp_fu_467_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_467_p_ce),
    .grp_fu_471_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din0),
    .grp_fu_471_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din1),
    .grp_fu_471_p_opcode(grp_transform_Pipeline_5_fu_289_grp_fu_471_p_opcode),
    .grp_fu_471_p_dout0(grp_fu_471_p2),
    .grp_fu_471_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_471_p_ce),
    .grp_fu_475_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din0),
    .grp_fu_475_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din1),
    .grp_fu_475_p_dout0(grp_fu_128_p_dout0),
    .grp_fu_475_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_475_p_ce),
    .grp_fu_479_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din0),
    .grp_fu_479_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din1),
    .grp_fu_479_p_dout0(grp_fu_132_p_dout0),
    .grp_fu_479_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_479_p_ce),
    .grp_fu_483_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din0),
    .grp_fu_483_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din1),
    .grp_fu_483_p_dout0(grp_fu_483_p2),
    .grp_fu_483_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_483_p_ce),
    .grp_fu_487_p_din0(grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din0),
    .grp_fu_487_p_din1(grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din1),
    .grp_fu_487_p_dout0(grp_fu_487_p2),
    .grp_fu_487_p_ce(grp_transform_Pipeline_5_fu_289_grp_fu_487_p_ce)
);

FFT_IP_fptrunc_64ns_32_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_3_no_dsp_1_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_412),
    .ce(grp_fu_302_ce),
    .dout(grp_fu_302_p1)
);

FFT_IP_fptrunc_64ns_32_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_3_no_dsp_1_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_417),
    .ce(grp_fu_305_ce),
    .dout(grp_fu_305_p1)
);

FFT_IP_faddfsub_32ns_32ns_32_10_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_10_full_dsp_1_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_471_p0),
    .din1(grp_fu_471_p1),
    .opcode(grp_fu_471_opcode),
    .ce(grp_fu_471_ce),
    .dout(grp_fu_471_p2)
);

FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_7_max_dsp_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_483_p0),
    .din1(grp_fu_483_p1),
    .ce(grp_fu_483_ce),
    .dout(grp_fu_483_p2)
);

FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_7_max_dsp_1_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_487_p0),
    .din1(grp_fu_487_p1),
    .ce(grp_fu_487_ce),
    .dout(grp_fu_487_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_s_fu_227_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sin_or_cos_double_s_fu_227_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_s_fu_227_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_s_fu_227_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_s_fu_243_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sin_or_cos_double_s_fu_243_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_s_fu_243_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_s_fu_243_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_1_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_transform_Pipeline_1_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_1_fu_215_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_1_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_4_fu_221_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_transform_Pipeline_4_fu_221_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_4_fu_221_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_4_fu_221_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_5_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_transform_Pipeline_5_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_5_fu_289_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_5_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln59_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg <= 1'b1;
        end else if ((grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_ready == 1'b1)) begin
            grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_56 <= 13'd2;
    end else if (((icmp_ln59_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i_fu_56 <= add_ln59_fu_322_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv3_i_reg_427 <= grp_fu_305_p1;
        conv_i_reg_422 <= grp_fu_302_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_reg_432 <= i_fu_56;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_n_reg_442 <= p_n_fu_333_p1;
        p_x_M_value_5_reg_447 <= W_M_value_q0;
        p_x_M_value_8_reg_457 <= p_x_M_value_8_fu_340_p3;
        p_x_M_value_9_reg_462 <= p_x_M_value_9_fu_349_p3;
        p_x_M_value_reg_452 <= W_M_value_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_1_reg_417 <= grp_sin_or_cos_double_s_fu_243_ap_return;
        tmp_reg_412 <= grp_sin_or_cos_double_s_fu_227_ap_return;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        W_M_value_1_address0 = this_M_value_14_reg_406;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_M_value_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        W_M_value_1_address0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_1_address0 = grp_transform_Pipeline_4_fu_221_W_M_value_1_address0;
    end else begin
        W_M_value_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        W_M_value_1_address1 = zext_ln59_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        W_M_value_1_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_1_address1 = 64'd0;
    end else begin
        W_M_value_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((icmp_ln59_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        W_M_value_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_1_ce0 = grp_transform_Pipeline_4_fu_221_W_M_value_1_ce0;
    end else begin
        W_M_value_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_1_ce1 = 1'b1;
    end else begin
        W_M_value_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1))) begin
        W_M_value_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_1_d0 = grp_transform_Pipeline_4_fu_221_W_M_value_1_d0;
    end else begin
        W_M_value_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        W_M_value_1_d1 = grp_transform_Pipeline_5_fu_289_agg_result_1_0_i_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        W_M_value_1_d1 = conv3_i_reg_427;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_1_d1 = 32'd0;
    end else begin
        W_M_value_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_1_we0 = grp_transform_Pipeline_4_fu_221_W_M_value_1_we0;
    end else begin
        W_M_value_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_1_we1 = 1'b1;
    end else begin
        W_M_value_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        W_M_value_address0 = this_M_value_13_reg_400;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        W_M_value_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        W_M_value_address0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_address0 = grp_transform_Pipeline_4_fu_221_W_M_value_address0;
    end else begin
        W_M_value_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        W_M_value_address1 = zext_ln59_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        W_M_value_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_address1 = 64'd0;
    end else begin
        W_M_value_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((icmp_ln59_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        W_M_value_ce0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_W_M_value_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_ce0 = grp_transform_Pipeline_4_fu_221_W_M_value_ce0;
    end else begin
        W_M_value_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_ce1 = 1'b1;
    end else begin
        W_M_value_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W_M_value_d0 = 32'd1065353216;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_d0 = grp_transform_Pipeline_4_fu_221_W_M_value_d0;
    end else begin
        W_M_value_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        W_M_value_d1 = grp_transform_Pipeline_5_fu_289_agg_result_0_0_i_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        W_M_value_d1 = conv_i_reg_422;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        W_M_value_d1 = 32'd0;
    end else begin
        W_M_value_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        W_M_value_we0 = grp_transform_Pipeline_4_fu_221_W_M_value_we0;
    end else begin
        W_M_value_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        W_M_value_we1 = 1'b1;
    end else begin
        W_M_value_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_transform_Pipeline_5_fu_289_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f2_M_value_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f2_M_value_1_address0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_1_address0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_1_address0 = grp_transform_Pipeline_1_fu_215_f2_M_value_1_address0;
    end else begin
        f2_M_value_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f2_M_value_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_1_ce0 = grp_transform_Pipeline_1_fu_215_f2_M_value_1_ce0;
    end else begin
        f2_M_value_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_1_ce1 = 1'b1;
    end else begin
        f2_M_value_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f2_M_value_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_1_d0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_1_d0 = grp_transform_Pipeline_1_fu_215_f2_M_value_1_d0;
    end else begin
        f2_M_value_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_1_we0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_1_we0 = grp_transform_Pipeline_1_fu_215_f2_M_value_1_we0;
    end else begin
        f2_M_value_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_1_we1 = 1'b1;
    end else begin
        f2_M_value_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f2_M_value_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f2_M_value_address0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_address0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_address0 = grp_transform_Pipeline_1_fu_215_f2_M_value_address0;
    end else begin
        f2_M_value_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f2_M_value_ce0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f2_M_value_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_ce0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_ce0 = grp_transform_Pipeline_1_fu_215_f2_M_value_ce0;
    end else begin
        f2_M_value_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_ce1 = 1'b1;
    end else begin
        f2_M_value_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f2_M_value_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_d0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_d0 = grp_transform_Pipeline_1_fu_215_f2_M_value_d0;
    end else begin
        f2_M_value_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f2_M_value_we0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f2_M_value_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f2_M_value_we0 = grp_transform_Pipeline_1_fu_215_f2_M_value_we0;
    end else begin
        f2_M_value_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f2_M_value_we1 = 1'b1;
    end else begin
        f2_M_value_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_0_address0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_0_address0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_0_address0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_address0;
    end else begin
        f_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_0_ce0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_0_ce0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_0_ce0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_0_ce0;
    end else begin
        f_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_0_ce1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_ce1;
    end else begin
        f_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_0_d0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_0_d0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_d0;
    end else begin
        f_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_0_we0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_0_we0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_0_we0;
    end else begin
        f_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_1_address0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_1_address0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_1_address0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_address0;
    end else begin
        f_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_1_ce0 = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_f_1_ce0;
    end else begin
        f_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_1_ce1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_ce1;
    end else begin
        f_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_1_d0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_1_d0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_d0;
    end else begin
        f_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f_1_we0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_1_we0 = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_f_1_we0;
    end else begin
        f_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done == 1'b1)))) begin
        grp_fu_302_ce = 1'b1;
    end else begin
        grp_fu_302_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done == 1'b1)))) begin
        grp_fu_305_ce = 1'b1;
    end else begin
        grp_fu_305_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_467_ce = grp_transform_Pipeline_5_fu_289_grp_fu_467_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_467_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_ce;
    end else begin
        grp_fu_467_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_467_opcode = grp_transform_Pipeline_5_fu_289_grp_fu_467_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_467_opcode = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_opcode;
    end else begin
        grp_fu_467_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_467_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_467_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din0;
    end else begin
        grp_fu_467_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_467_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_467_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_467_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_467_p_din1;
    end else begin
        grp_fu_467_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_471_ce = grp_transform_Pipeline_5_fu_289_grp_fu_471_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_471_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_ce;
    end else begin
        grp_fu_471_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_471_opcode = grp_transform_Pipeline_5_fu_289_grp_fu_471_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_471_opcode = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_opcode;
    end else begin
        grp_fu_471_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_471_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_471_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din0;
    end else begin
        grp_fu_471_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_471_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_471_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_471_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_471_p_din1;
    end else begin
        grp_fu_471_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_475_ce = grp_transform_Pipeline_5_fu_289_grp_fu_475_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_475_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_ce;
    end else begin
        grp_fu_475_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_475_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_475_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din0;
    end else begin
        grp_fu_475_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_475_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_475_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_475_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_475_p_din1;
    end else begin
        grp_fu_475_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_479_ce = grp_transform_Pipeline_5_fu_289_grp_fu_479_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_479_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_ce;
    end else begin
        grp_fu_479_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_479_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_479_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din0;
    end else begin
        grp_fu_479_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_479_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_479_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_479_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_479_p_din1;
    end else begin
        grp_fu_479_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_483_ce = grp_transform_Pipeline_5_fu_289_grp_fu_483_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_483_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_ce;
    end else begin
        grp_fu_483_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_483_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_483_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din0;
    end else begin
        grp_fu_483_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_483_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_483_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_483_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_483_p_din1;
    end else begin
        grp_fu_483_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_487_ce = grp_transform_Pipeline_5_fu_289_grp_fu_487_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_487_ce = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_ce;
    end else begin
        grp_fu_487_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_487_p0 = grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_487_p0 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din0;
    end else begin
        grp_fu_487_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_487_p1 = grp_transform_Pipeline_5_fu_289_grp_fu_487_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_487_p1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_grp_fu_487_p_din1;
    end else begin
        grp_fu_487_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln59_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_transform_Pipeline_5_fu_289_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_fu_322_p2 = (i_fu_56 + 13'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_sin_or_cos_double_s_fu_243_ap_done == 1'b0) | (grp_sin_or_cos_double_s_fu_227_ap_done == 1'b0) | (grp_transform_Pipeline_4_fu_221_ap_done == 1'b0) | (grp_transform_Pipeline_1_fu_215_ap_done == 1'b0));
end

assign f2_M_value_1_address1 = 64'd0;

assign f2_M_value_address1 = 64'd0;

assign f_0_address1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_0_address1;

assign f_1_address1 = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_f_1_address1;

assign grp_fu_124_p_ce = grp_fu_467_ce;

assign grp_fu_124_p_din0 = grp_fu_467_p0;

assign grp_fu_124_p_din1 = grp_fu_467_p1;

assign grp_fu_124_p_opcode = grp_fu_467_opcode;

assign grp_fu_128_p_ce = grp_fu_475_ce;

assign grp_fu_128_p_din0 = grp_fu_475_p0;

assign grp_fu_128_p_din1 = grp_fu_475_p1;

assign grp_fu_132_p_ce = grp_fu_479_ce;

assign grp_fu_132_p_din0 = grp_fu_479_p0;

assign grp_fu_132_p_din1 = grp_fu_479_p1;

assign grp_sin_or_cos_double_s_fu_227_ap_start = grp_sin_or_cos_double_s_fu_227_ap_start_reg;

assign grp_sin_or_cos_double_s_fu_227_do_cos = 1'd1;

assign grp_sin_or_cos_double_s_fu_243_ap_start = grp_sin_or_cos_double_s_fu_243_ap_start_reg;

assign grp_sin_or_cos_double_s_fu_243_do_cos = 1'd0;

assign grp_transform_Pipeline_1_fu_215_ap_start = grp_transform_Pipeline_1_fu_215_ap_start_reg;

assign grp_transform_Pipeline_4_fu_221_ap_start = grp_transform_Pipeline_4_fu_221_ap_start_reg;

assign grp_transform_Pipeline_5_fu_289_ap_start = grp_transform_Pipeline_5_fu_289_ap_start_reg;

assign grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start = grp_transform_Pipeline_VITIS_LOOP_44_1_fu_259_ap_start_reg;

assign grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start = grp_transform_Pipeline_VITIS_LOOP_47_2_fu_269_ap_start_reg;

assign grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start = grp_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3_fu_279_ap_start_reg;

assign icmp_ln59_fu_316_p2 = ((i_fu_56 == 13'd4096) ? 1'b1 : 1'b0);

assign p_n_fu_333_p1 = i_1_reg_432[11:0];

assign p_x_M_value_8_fu_340_p3 = ((trunc_ln60_1_fu_337_p1[0:0] == 1'b1) ? W_M_value_q0 : 32'd1065353216);

assign p_x_M_value_9_fu_349_p3 = ((trunc_ln60_1_fu_337_p1[0:0] == 1'b1) ? W_M_value_1_q0 : 32'd0);

assign this_M_value_13_reg_400 = 64'd1;

assign this_M_value_14_reg_406 = 64'd1;

assign trunc_ln60_1_fu_337_p1 = i_1_reg_432[0:0];

assign zext_ln59_fu_358_p1 = i_1_reg_432;

endmodule //FFT_IP_transform
