// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FFT_IP_sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   do_cos;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] fourth_order_double_sin_cos_K0_V_address0;
reg    fourth_order_double_sin_cos_K0_V_ce0;
wire   [58:0] fourth_order_double_sin_cos_K0_V_q0;
wire   [7:0] fourth_order_double_sin_cos_K1_V_address0;
reg    fourth_order_double_sin_cos_K1_V_ce0;
wire   [51:0] fourth_order_double_sin_cos_K1_V_q0;
wire   [7:0] fourth_order_double_sin_cos_K2_V_address0;
reg    fourth_order_double_sin_cos_K2_V_ce0;
wire   [43:0] fourth_order_double_sin_cos_K2_V_q0;
wire   [7:0] fourth_order_double_sin_cos_K3_V_address0;
reg    fourth_order_double_sin_cos_K3_V_ce0;
wire   [32:0] fourth_order_double_sin_cos_K3_V_q0;
wire   [7:0] fourth_order_double_sin_cos_K4_V_address0;
reg    fourth_order_double_sin_cos_K4_V_ce0;
wire   [24:0] fourth_order_double_sin_cos_K4_V_q0;
wire   [0:0] sin_basis_fu_262_p2;
reg   [0:0] sin_basis_reg_667;
wire   [63:0] zext_ln541_fu_276_p1;
reg   [63:0] zext_ln541_reg_672;
reg  signed [51:0] fourth_order_double_sin_cos_K1_V_load_reg_685;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg  signed [43:0] fourth_order_double_sin_cos_K2_V_load_reg_705;
wire    ap_CS_fsm_state4;
reg   [32:0] fourth_order_double_sin_cos_K3_V_load_reg_710;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [58:0] fourth_order_double_sin_cos_K0_V_load_reg_735;
wire    ap_CS_fsm_state7;
reg   [52:0] trunc_ln_reg_740;
reg   [41:0] trunc_ln818_1_reg_745;
reg   [16:0] rhs_1_reg_750;
reg   [27:0] trunc_ln2_reg_755;
wire   [63:0] ret_V_fu_407_p2;
reg  signed [63:0] ret_V_reg_760;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [62:0] in_shift_V_reg_775;
wire    ap_CS_fsm_state13;
reg   [14:0] tmp_reg_782;
wire   [31:0] p_Result_1_fu_461_p3;
reg   [31:0] p_Result_1_reg_796;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln1653_fu_485_p2;
reg   [0:0] icmp_ln1653_reg_813;
wire    ap_CS_fsm_state18;
wire   [0:0] grp_sin_or_cos_double_Pipeline_3_fu_249_ap_return;
reg   [0:0] targetBlock_reg_818;
wire    ap_CS_fsm_state19;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_ap_done;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_2_03_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_2_03_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_1_02_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_1_02_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_0_01_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_0_01_out_ap_vld;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_ap_done;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_237_c_2_07_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_c_2_07_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_237_c_1_06_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_c_1_06_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_237_c_0_05_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_c_0_05_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_237_c_3_04_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_237_c_3_04_out_ap_vld;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_ap_done;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out_ap_vld;
wire   [61:0] grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out_ap_vld;
wire   [61:0] grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out_ap_vld;
reg    grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg;
wire    ap_CS_fsm_state17;
reg    grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg;
reg   [31:0] shift_loc_fu_126;
reg   [61:0] in_shift_V_loc_fu_122;
reg   [31:0] shift_1_loc_fu_118;
reg   [61:0] r_V_8_loc_fu_114;
wire    ap_CS_fsm_state20;
wire   [0:0] sin_basis_fu_262_p0;
wire   [7:0] p_Result_s_fu_268_p3;
wire   [53:0] grp_fu_284_p1;
wire   [43:0] grp_fu_293_p1;
wire   [32:0] grp_fu_302_p0;
wire   [33:0] grp_fu_302_p1;
wire   [104:0] grp_fu_284_p2;
wire   [86:0] grp_fu_293_p2;
wire   [47:0] shl_ln_fu_332_p3;
wire   [47:0] zext_ln1273_1_fu_328_p1;
wire   [47:0] r_V_7_fu_340_p2;
wire   [65:0] grp_fu_302_p2;
wire   [62:0] t1_V_fu_366_p3;
wire  signed [63:0] sext_ln813_fu_373_p1;
wire  signed [63:0] sext_ln813_1_fu_377_p1;
wire   [63:0] ret_V_4_fu_380_p2;
wire  signed [63:0] sext_ln1347_fu_386_p1;
wire   [63:0] ret_V_5_fu_389_p2;
wire   [63:0] zext_ln1347_fu_395_p1;
wire   [63:0] ret_V_6_fu_398_p2;
wire   [63:0] zext_ln1347_1_fu_404_p1;
wire   [0:0] select_ln1273_fu_413_p0;
wire  signed [63:0] grp_fu_423_p0;
wire   [125:0] grp_fu_423_p2;
wire   [0:0] select_ln461_fu_509_p0;
wire   [31:0] select_ln461_fu_509_p3;
wire   [31:0] select_ln450_fu_502_p3;
wire   [31:0] newexp_fu_516_p2;
wire   [0:0] tmp_12_fu_522_p3;
wire   [51:0] tmp_13_fu_535_p4;
wire   [51:0] tmp_14_fu_545_p4;
wire   [0:0] or_ln462_fu_530_p2;
wire   [51:0] select_ln450_1_fu_555_p3;
wire   [10:0] empty_fu_562_p1;
wire   [10:0] out_exp_V_fu_574_p3;
wire   [51:0] significand_fu_566_p3;
wire   [63:0] p_Result_2_fu_582_p4;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire   [65:0] grp_fu_302_p00;
wire  signed [125:0] grp_fu_423_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg = 1'b0;
end

FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K0_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K0_V_address0),
    .ce0(fourth_order_double_sin_cos_K0_V_ce0),
    .q0(fourth_order_double_sin_cos_K0_V_q0)
);

FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K1_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K1_V_address0),
    .ce0(fourth_order_double_sin_cos_K1_V_ce0),
    .q0(fourth_order_double_sin_cos_K1_V_q0)
);

FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K2_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K2_V_address0),
    .ce0(fourth_order_double_sin_cos_K2_V_ce0),
    .q0(fourth_order_double_sin_cos_K2_V_q0)
);

FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K3_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K3_V_address0),
    .ce0(fourth_order_double_sin_cos_K3_V_ce0),
    .q0(fourth_order_double_sin_cos_K3_V_q0)
);

FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K4_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K4_V_address0),
    .ce0(fourth_order_double_sin_cos_K4_V_ce0),
    .q0(fourth_order_double_sin_cos_K4_V_q0)
);

FFT_IP_sin_or_cos_double_Pipeline_1 grp_sin_or_cos_double_Pipeline_1_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_1_fu_229_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_1_fu_229_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_1_fu_229_ap_ready),
    .in_shift_V_3(in_shift_V_reg_775),
    .out_bits_V_2_03_out(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_2_03_out),
    .out_bits_V_2_03_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_2_03_out_ap_vld),
    .out_bits_V_1_02_out(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_1_02_out),
    .out_bits_V_1_02_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_1_02_out_ap_vld),
    .out_bits_V_0_01_out(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_0_01_out),
    .out_bits_V_0_01_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_0_01_out_ap_vld)
);

FFT_IP_sin_or_cos_double_Pipeline_2 grp_sin_or_cos_double_Pipeline_2_fu_237(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_2_fu_237_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_2_fu_237_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_2_fu_237_ap_ready),
    .out_bits_V_0_01_reload(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_0_01_out),
    .out_bits_V_1_02_reload(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_1_02_out),
    .out_bits_V_2_03_reload(grp_sin_or_cos_double_Pipeline_1_fu_229_out_bits_V_2_03_out),
    .p_Result_1(p_Result_1_reg_796),
    .c_2_07_out(grp_sin_or_cos_double_Pipeline_2_fu_237_c_2_07_out),
    .c_2_07_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_237_c_2_07_out_ap_vld),
    .c_1_06_out(grp_sin_or_cos_double_Pipeline_2_fu_237_c_1_06_out),
    .c_1_06_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_237_c_1_06_out_ap_vld),
    .c_0_05_out(grp_sin_or_cos_double_Pipeline_2_fu_237_c_0_05_out),
    .c_0_05_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_237_c_0_05_out_ap_vld),
    .c_3_04_out(grp_sin_or_cos_double_Pipeline_2_fu_237_c_3_04_out),
    .c_3_04_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_237_c_3_04_out_ap_vld)
);

FFT_IP_sin_or_cos_double_Pipeline_3 grp_sin_or_cos_double_Pipeline_3_fu_249(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_3_fu_249_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_3_fu_249_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_3_fu_249_ap_ready),
    .in_shift_V_3(in_shift_V_reg_775),
    .c_0_05_reload(grp_sin_or_cos_double_Pipeline_2_fu_237_c_0_05_out),
    .c_1_06_reload(grp_sin_or_cos_double_Pipeline_2_fu_237_c_1_06_out),
    .c_2_07_reload(grp_sin_or_cos_double_Pipeline_2_fu_237_c_2_07_out),
    .c_3_04_reload(grp_sin_or_cos_double_Pipeline_2_fu_237_c_3_04_out),
    .shift_out(grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out),
    .shift_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out_ap_vld),
    .in_shift_V_out(grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out),
    .in_shift_V_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out_ap_vld),
    .shift_1_out(grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out),
    .shift_1_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out_ap_vld),
    .r_V_8_out(grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out),
    .r_V_8_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out_ap_vld),
    .ap_return(grp_sin_or_cos_double_Pipeline_3_fu_249_ap_return)
);

FFT_IP_mul_52s_54ns_105_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 52 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 105 ))
mul_52s_54ns_105_5_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fourth_order_double_sin_cos_K1_V_load_reg_685),
    .din1(grp_fu_284_p1),
    .ce(1'b1),
    .dout(grp_fu_284_p2)
);

FFT_IP_mul_44s_44ns_87_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 87 ))
mul_44s_44ns_87_3_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(fourth_order_double_sin_cos_K2_V_load_reg_705),
    .din1(grp_fu_293_p1),
    .ce(1'b1),
    .dout(grp_fu_293_p2)
);

FFT_IP_mul_33ns_34ns_66_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 66 ))
mul_33ns_34ns_66_3_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_302_p0),
    .din1(grp_fu_302_p1),
    .ce(1'b1),
    .dout(grp_fu_302_p2)
);

FFT_IP_mul_64s_64s_126_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 126 ))
mul_64s_64s_126_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_423_p0),
    .din1(ret_V_reg_760),
    .ce(1'b1),
    .dout(grp_fu_423_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_1_fu_229_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_2_fu_237_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_3_fu_249_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fourth_order_double_sin_cos_K0_V_load_reg_735 <= fourth_order_double_sin_cos_K0_V_q0;
        rhs_1_reg_750 <= {{r_V_7_fu_340_p2[47:31]}};
        trunc_ln2_reg_755 <= {{grp_fu_302_p2[65:38]}};
        trunc_ln818_1_reg_745 <= {{grp_fu_293_p2[86:45]}};
        trunc_ln_reg_740 <= {{grp_fu_284_p2[104:52]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fourth_order_double_sin_cos_K1_V_load_reg_685 <= fourth_order_double_sin_cos_K1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fourth_order_double_sin_cos_K2_V_load_reg_705 <= fourth_order_double_sin_cos_K2_V_q0;
        fourth_order_double_sin_cos_K3_V_load_reg_710 <= fourth_order_double_sin_cos_K3_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln1653_reg_813 <= icmp_ln1653_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        in_shift_V_loc_fu_122 <= grp_sin_or_cos_double_Pipeline_3_fu_249_in_shift_V_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        in_shift_V_reg_775 <= {{grp_fu_423_p2[125:63]}};
        tmp_reg_782 <= {{grp_fu_423_p2[77:63]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        p_Result_1_reg_796[31 : 17] <= p_Result_1_fu_461_p3[31 : 17];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        r_V_8_loc_fu_114 <= grp_sin_or_cos_double_Pipeline_3_fu_249_r_V_8_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ret_V_reg_760 <= ret_V_fu_407_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        shift_1_loc_fu_118 <= grp_sin_or_cos_double_Pipeline_3_fu_249_shift_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        shift_loc_fu_126 <= grp_sin_or_cos_double_Pipeline_3_fu_249_shift_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sin_basis_reg_667 <= sin_basis_fu_262_p2;
        zext_ln541_reg_672[7] <= zext_ln541_fu_276_p1[7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        targetBlock_reg_818 <= grp_sin_or_cos_double_Pipeline_3_fu_249_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_1_fu_229_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_2_fu_237_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_3_fu_249_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fourth_order_double_sin_cos_K0_V_ce0 = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        fourth_order_double_sin_cos_K1_V_ce0 = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fourth_order_double_sin_cos_K2_V_ce0 = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fourth_order_double_sin_cos_K3_V_ce0 = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fourth_order_double_sin_cos_K4_V_ce0 = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_sin_or_cos_double_Pipeline_1_fu_229_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_sin_or_cos_double_Pipeline_2_fu_237_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_sin_or_cos_double_Pipeline_3_fu_249_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = p_Result_2_fu_582_p4;

assign empty_fu_562_p1 = newexp_fu_516_p2[10:0];

assign fourth_order_double_sin_cos_K0_V_address0 = zext_ln541_reg_672;

assign fourth_order_double_sin_cos_K1_V_address0 = zext_ln541_fu_276_p1;

assign fourth_order_double_sin_cos_K2_V_address0 = zext_ln541_reg_672;

assign fourth_order_double_sin_cos_K3_V_address0 = zext_ln541_reg_672;

assign fourth_order_double_sin_cos_K4_V_address0 = zext_ln541_reg_672;

assign grp_fu_284_p1 = 105'd9007199254740991;

assign grp_fu_293_p1 = 87'd8796093022207;

assign grp_fu_302_p0 = grp_fu_302_p00;

assign grp_fu_302_p00 = fourth_order_double_sin_cos_K3_V_load_reg_710;

assign grp_fu_302_p1 = 66'd8589934591;

assign grp_fu_423_p0 = grp_fu_423_p00;

assign grp_fu_423_p00 = ((select_ln1273_fu_413_p0[0:0] == 1'b1) ? 126'd9223372036854775807 : 126'd9223372036854775448);

assign grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start = grp_sin_or_cos_double_Pipeline_1_fu_229_ap_start_reg;

assign grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start = grp_sin_or_cos_double_Pipeline_2_fu_237_ap_start_reg;

assign grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start = grp_sin_or_cos_double_Pipeline_3_fu_249_ap_start_reg;

assign icmp_ln1653_fu_485_p2 = ((in_shift_V_reg_775 == 63'd0) ? 1'b1 : 1'b0);

assign newexp_fu_516_p2 = (select_ln461_fu_509_p3 - select_ln450_fu_502_p3);

assign or_ln462_fu_530_p2 = (tmp_12_fu_522_p3 | icmp_ln1653_reg_813);

assign out_exp_V_fu_574_p3 = ((or_ln462_fu_530_p2[0:0] == 1'b1) ? 11'd0 : empty_fu_562_p1);

assign p_Result_1_fu_461_p3 = {{tmp_reg_782}, {17'd65536}};

assign p_Result_2_fu_582_p4 = {{{sin_basis_reg_667}, {out_exp_V_fu_574_p3}}, {significand_fu_566_p3}};

assign p_Result_s_fu_268_p3 = {{sin_basis_fu_262_p2}, {7'd0}};

assign r_V_7_fu_340_p2 = (shl_ln_fu_332_p3 - zext_ln1273_1_fu_328_p1);

assign ret_V_4_fu_380_p2 = ($signed(sext_ln813_fu_373_p1) + $signed(sext_ln813_1_fu_377_p1));

assign ret_V_5_fu_389_p2 = ($signed(ret_V_4_fu_380_p2) + $signed(sext_ln1347_fu_386_p1));

assign ret_V_6_fu_398_p2 = (ret_V_5_fu_389_p2 + zext_ln1347_fu_395_p1);

assign ret_V_fu_407_p2 = (ret_V_6_fu_398_p2 + zext_ln1347_1_fu_404_p1);

assign select_ln1273_fu_413_p0 = do_cos;

assign select_ln450_1_fu_555_p3 = ((targetBlock_reg_818[0:0] == 1'b1) ? tmp_13_fu_535_p4 : tmp_14_fu_545_p4);

assign select_ln450_fu_502_p3 = ((targetBlock_reg_818[0:0] == 1'b1) ? shift_loc_fu_126 : shift_1_loc_fu_118);

assign select_ln461_fu_509_p0 = do_cos;

assign select_ln461_fu_509_p3 = ((select_ln461_fu_509_p0[0:0] == 1'b1) ? 32'd1023 : 32'd1013);

assign sext_ln1347_fu_386_p1 = $signed(trunc_ln818_1_reg_745);

assign sext_ln813_1_fu_377_p1 = $signed(trunc_ln_reg_740);

assign sext_ln813_fu_373_p1 = $signed(t1_V_fu_366_p3);

assign shl_ln_fu_332_p3 = {{fourth_order_double_sin_cos_K4_V_q0}, {23'd0}};

assign significand_fu_566_p3 = ((or_ln462_fu_530_p2[0:0] == 1'b1) ? 52'd0 : select_ln450_1_fu_555_p3);

assign sin_basis_fu_262_p0 = do_cos;

assign sin_basis_fu_262_p2 = (sin_basis_fu_262_p0 ^ 1'd1);

assign t1_V_fu_366_p3 = {{fourth_order_double_sin_cos_K0_V_load_reg_735}, {4'd0}};

assign tmp_12_fu_522_p3 = newexp_fu_516_p2[32'd31];

assign tmp_13_fu_535_p4 = {{in_shift_V_loc_fu_122[61:10]}};

assign tmp_14_fu_545_p4 = {{r_V_8_loc_fu_114[61:10]}};

assign zext_ln1273_1_fu_328_p1 = fourth_order_double_sin_cos_K4_V_q0;

assign zext_ln1347_1_fu_404_p1 = rhs_1_reg_750;

assign zext_ln1347_fu_395_p1 = trunc_ln2_reg_755;

assign zext_ln541_fu_276_p1 = p_Result_s_fu_268_p3;

always @ (posedge ap_clk) begin
    zext_ln541_reg_672[6:0] <= 7'b0000000;
    zext_ln541_reg_672[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    p_Result_1_reg_796[16:0] <= 17'b10000000000000000;
end

endmodule //FFT_IP_sin_or_cos_double_s
