// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FFT_IP_FFT_IP,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.919312,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=96,HLS_SYN_DSP=0,HLS_SYN_FF=11135,HLS_SYN_LUT=11901,HLS_VERSION=2022_2}" *)

module FFT_IP (
        ap_clk,
        ap_rst_n,
        ExtVolDataIn_Addr_A,
        ExtVolDataIn_EN_A,
        ExtVolDataIn_WEN_A,
        ExtVolDataIn_Din_A,
        ExtVolDataIn_Dout_A,
        ExtVolDataIn_Clk_A,
        ExtVolDataIn_Rst_A,
        ExtVolDataOut_Addr_A,
        ExtVolDataOut_EN_A,
        ExtVolDataOut_WEN_A,
        ExtVolDataOut_Din_A,
        ExtVolDataOut_Dout_A,
        ExtVolDataOut_Clk_A,
        ExtVolDataOut_Rst_A,
        s_axi_BUS_A_AWVALID,
        s_axi_BUS_A_AWREADY,
        s_axi_BUS_A_AWADDR,
        s_axi_BUS_A_WVALID,
        s_axi_BUS_A_WREADY,
        s_axi_BUS_A_WDATA,
        s_axi_BUS_A_WSTRB,
        s_axi_BUS_A_ARVALID,
        s_axi_BUS_A_ARREADY,
        s_axi_BUS_A_ARADDR,
        s_axi_BUS_A_RVALID,
        s_axi_BUS_A_RREADY,
        s_axi_BUS_A_RDATA,
        s_axi_BUS_A_RRESP,
        s_axi_BUS_A_BVALID,
        s_axi_BUS_A_BREADY,
        s_axi_BUS_A_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_BUS_A_DATA_WIDTH = 32;
parameter    C_S_AXI_BUS_A_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BUS_A_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] ExtVolDataIn_Addr_A;
output   ExtVolDataIn_EN_A;
output  [3:0] ExtVolDataIn_WEN_A;
output  [31:0] ExtVolDataIn_Din_A;
input  [31:0] ExtVolDataIn_Dout_A;
output   ExtVolDataIn_Clk_A;
output   ExtVolDataIn_Rst_A;
output  [31:0] ExtVolDataOut_Addr_A;
output   ExtVolDataOut_EN_A;
output  [3:0] ExtVolDataOut_WEN_A;
output  [31:0] ExtVolDataOut_Din_A;
input  [31:0] ExtVolDataOut_Dout_A;
output   ExtVolDataOut_Clk_A;
output   ExtVolDataOut_Rst_A;
input   s_axi_BUS_A_AWVALID;
output   s_axi_BUS_A_AWREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_AWADDR;
input   s_axi_BUS_A_WVALID;
output   s_axi_BUS_A_WREADY;
input  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_WDATA;
input  [C_S_AXI_BUS_A_WSTRB_WIDTH - 1:0] s_axi_BUS_A_WSTRB;
input   s_axi_BUS_A_ARVALID;
output   s_axi_BUS_A_ARREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_ARADDR;
output   s_axi_BUS_A_RVALID;
input   s_axi_BUS_A_RREADY;
output  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_RDATA;
output  [1:0] s_axi_BUS_A_RRESP;
output   s_axi_BUS_A_BVALID;
input   s_axi_BUS_A_BREADY;
output  [1:0] s_axi_BUS_A_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [12:0] f_M_value_address0;
reg    f_M_value_ce0;
reg    f_M_value_we0;
reg   [31:0] f_M_value_d0;
wire   [31:0] f_M_value_q0;
reg    f_M_value_ce1;
wire   [31:0] f_M_value_q1;
reg   [12:0] f_M_value_1_address0;
reg    f_M_value_1_ce0;
reg    f_M_value_1_we0;
reg   [31:0] f_M_value_1_d0;
wire   [31:0] f_M_value_1_q0;
reg    f_M_value_1_ce1;
wire   [31:0] f_M_value_1_q1;
wire    grp_FFT_IP_Pipeline_1_fu_86_ap_start;
wire    grp_FFT_IP_Pipeline_1_fu_86_ap_done;
wire    grp_FFT_IP_Pipeline_1_fu_86_ap_idle;
wire    grp_FFT_IP_Pipeline_1_fu_86_ap_ready;
wire   [12:0] grp_FFT_IP_Pipeline_1_fu_86_f_M_value_address0;
wire    grp_FFT_IP_Pipeline_1_fu_86_f_M_value_ce0;
wire    grp_FFT_IP_Pipeline_1_fu_86_f_M_value_we0;
wire   [31:0] grp_FFT_IP_Pipeline_1_fu_86_f_M_value_d0;
wire   [12:0] grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_address0;
wire    grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_ce0;
wire    grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_we0;
wire   [31:0] grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_d0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_done;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_idle;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_ready;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_Addr_A;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_EN_A;
wire   [3:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_WEN_A;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_Din_A;
wire   [12:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_address0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_ce0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_we0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_d0;
wire   [12:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_address0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_ce0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_we0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_d0;
wire    grp_transform_fu_100_ap_start;
wire    grp_transform_fu_100_ap_done;
wire    grp_transform_fu_100_ap_idle;
wire    grp_transform_fu_100_ap_ready;
wire   [12:0] grp_transform_fu_100_f_0_address0;
wire    grp_transform_fu_100_f_0_ce0;
wire    grp_transform_fu_100_f_0_we0;
wire   [31:0] grp_transform_fu_100_f_0_d0;
wire   [12:0] grp_transform_fu_100_f_0_address1;
wire    grp_transform_fu_100_f_0_ce1;
wire   [12:0] grp_transform_fu_100_f_1_address0;
wire    grp_transform_fu_100_f_1_ce0;
wire    grp_transform_fu_100_f_1_we0;
wire   [31:0] grp_transform_fu_100_f_1_d0;
wire   [12:0] grp_transform_fu_100_f_1_address1;
wire    grp_transform_fu_100_f_1_ce1;
wire   [31:0] grp_transform_fu_100_grp_fu_124_p_din0;
wire   [31:0] grp_transform_fu_100_grp_fu_124_p_din1;
wire   [1:0] grp_transform_fu_100_grp_fu_124_p_opcode;
wire    grp_transform_fu_100_grp_fu_124_p_ce;
wire   [31:0] grp_transform_fu_100_grp_fu_128_p_din0;
wire   [31:0] grp_transform_fu_100_grp_fu_128_p_din1;
wire    grp_transform_fu_100_grp_fu_128_p_ce;
wire   [31:0] grp_transform_fu_100_grp_fu_132_p_din0;
wire   [31:0] grp_transform_fu_100_grp_fu_132_p_din1;
wire    grp_transform_fu_100_grp_fu_132_p_ce;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_idle;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_ready;
wire   [12:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_address0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_ce0;
wire   [12:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_address0;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_ce0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Addr_A;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_EN_A;
wire   [3:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_WEN_A;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Din_A;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din1;
wire   [0:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_opcode;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_ce;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din1;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_ce;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din0;
wire   [31:0] grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din1;
wire    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_ce;
reg    grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_transform_fu_100_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_124_p2;
reg   [31:0] grp_fu_124_p0;
reg   [31:0] grp_fu_124_p1;
reg   [1:0] grp_fu_124_opcode;
reg    grp_fu_124_ce;
wire   [31:0] grp_fu_128_p2;
reg   [31:0] grp_fu_128_p0;
reg   [31:0] grp_fu_128_p1;
reg    grp_fu_128_ce;
wire   [31:0] grp_fu_132_p2;
reg   [31:0] grp_fu_132_p0;
reg   [31:0] grp_fu_132_p1;
reg    grp_fu_132_ce;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg = 1'b0;
#0 grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg = 1'b0;
#0 grp_transform_fu_100_ap_start_reg = 1'b0;
#0 grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg = 1'b0;
end

FFT_IP_f_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
f_M_value_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(f_M_value_address0),
    .ce0(f_M_value_ce0),
    .we0(f_M_value_we0),
    .d0(f_M_value_d0),
    .q0(f_M_value_q0),
    .address1(grp_transform_fu_100_f_0_address1),
    .ce1(f_M_value_ce1),
    .q1(f_M_value_q1)
);

FFT_IP_f_M_value_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
f_M_value_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(f_M_value_1_address0),
    .ce0(f_M_value_1_ce0),
    .we0(f_M_value_1_we0),
    .d0(f_M_value_1_d0),
    .q0(f_M_value_1_q0),
    .address1(grp_transform_fu_100_f_1_address1),
    .ce1(f_M_value_1_ce1),
    .q1(f_M_value_1_q1)
);

FFT_IP_FFT_IP_Pipeline_1 grp_FFT_IP_Pipeline_1_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FFT_IP_Pipeline_1_fu_86_ap_start),
    .ap_done(grp_FFT_IP_Pipeline_1_fu_86_ap_done),
    .ap_idle(grp_FFT_IP_Pipeline_1_fu_86_ap_idle),
    .ap_ready(grp_FFT_IP_Pipeline_1_fu_86_ap_ready),
    .f_M_value_address0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_address0),
    .f_M_value_ce0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_ce0),
    .f_M_value_we0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_we0),
    .f_M_value_d0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_d0),
    .f_M_value_1_address0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_address0),
    .f_M_value_1_ce0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_ce0),
    .f_M_value_1_we0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_we0),
    .f_M_value_1_d0(grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_d0)
);

FFT_IP_FFT_IP_Pipeline_VITIS_LOOP_97_1 grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start),
    .ap_done(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_done),
    .ap_idle(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_idle),
    .ap_ready(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_ready),
    .ExtVolDataIn_Addr_A(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_Addr_A),
    .ExtVolDataIn_EN_A(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_EN_A),
    .ExtVolDataIn_WEN_A(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_WEN_A),
    .ExtVolDataIn_Din_A(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_Din_A),
    .ExtVolDataIn_Dout_A(ExtVolDataIn_Dout_A),
    .f_M_value_address0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_address0),
    .f_M_value_ce0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_ce0),
    .f_M_value_we0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_we0),
    .f_M_value_d0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_d0),
    .f_M_value_1_address0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_address0),
    .f_M_value_1_ce0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_ce0),
    .f_M_value_1_we0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_we0),
    .f_M_value_1_d0(grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_d0)
);

FFT_IP_transform grp_transform_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_transform_fu_100_ap_start),
    .ap_done(grp_transform_fu_100_ap_done),
    .ap_idle(grp_transform_fu_100_ap_idle),
    .ap_ready(grp_transform_fu_100_ap_ready),
    .f_0_address0(grp_transform_fu_100_f_0_address0),
    .f_0_ce0(grp_transform_fu_100_f_0_ce0),
    .f_0_we0(grp_transform_fu_100_f_0_we0),
    .f_0_d0(grp_transform_fu_100_f_0_d0),
    .f_0_q0(f_M_value_q0),
    .f_0_address1(grp_transform_fu_100_f_0_address1),
    .f_0_ce1(grp_transform_fu_100_f_0_ce1),
    .f_0_q1(f_M_value_q1),
    .f_1_address0(grp_transform_fu_100_f_1_address0),
    .f_1_ce0(grp_transform_fu_100_f_1_ce0),
    .f_1_we0(grp_transform_fu_100_f_1_we0),
    .f_1_d0(grp_transform_fu_100_f_1_d0),
    .f_1_q0(f_M_value_1_q0),
    .f_1_address1(grp_transform_fu_100_f_1_address1),
    .f_1_ce1(grp_transform_fu_100_f_1_ce1),
    .f_1_q1(f_M_value_1_q1),
    .grp_fu_124_p_din0(grp_transform_fu_100_grp_fu_124_p_din0),
    .grp_fu_124_p_din1(grp_transform_fu_100_grp_fu_124_p_din1),
    .grp_fu_124_p_opcode(grp_transform_fu_100_grp_fu_124_p_opcode),
    .grp_fu_124_p_dout0(grp_fu_124_p2),
    .grp_fu_124_p_ce(grp_transform_fu_100_grp_fu_124_p_ce),
    .grp_fu_128_p_din0(grp_transform_fu_100_grp_fu_128_p_din0),
    .grp_fu_128_p_din1(grp_transform_fu_100_grp_fu_128_p_din1),
    .grp_fu_128_p_dout0(grp_fu_128_p2),
    .grp_fu_128_p_ce(grp_transform_fu_100_grp_fu_128_p_ce),
    .grp_fu_132_p_din0(grp_transform_fu_100_grp_fu_132_p_din0),
    .grp_fu_132_p_din1(grp_transform_fu_100_grp_fu_132_p_din1),
    .grp_fu_132_p_dout0(grp_fu_132_p2),
    .grp_fu_132_p_ce(grp_transform_fu_100_grp_fu_132_p_ce)
);

FFT_IP_FFT_IP_Pipeline_VITIS_LOOP_112_3 grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start),
    .ap_done(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done),
    .ap_idle(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_idle),
    .ap_ready(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_ready),
    .f_M_value_address0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_address0),
    .f_M_value_ce0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_ce0),
    .f_M_value_q0(f_M_value_q0),
    .f_M_value_1_address0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_address0),
    .f_M_value_1_ce0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_ce0),
    .f_M_value_1_q0(f_M_value_1_q0),
    .ExtVolDataOut_Addr_A(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Addr_A),
    .ExtVolDataOut_EN_A(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_EN_A),
    .ExtVolDataOut_WEN_A(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_WEN_A),
    .ExtVolDataOut_Din_A(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Din_A),
    .ExtVolDataOut_Dout_A(32'd0),
    .grp_fu_124_p_din0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din0),
    .grp_fu_124_p_din1(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din1),
    .grp_fu_124_p_opcode(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_opcode),
    .grp_fu_124_p_dout0(grp_fu_124_p2),
    .grp_fu_124_p_ce(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_ce),
    .grp_fu_128_p_din0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din0),
    .grp_fu_128_p_din1(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din1),
    .grp_fu_128_p_dout0(grp_fu_128_p2),
    .grp_fu_128_p_ce(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_ce),
    .grp_fu_132_p_din0(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din0),
    .grp_fu_132_p_din1(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din1),
    .grp_fu_132_p_dout0(grp_fu_132_p2),
    .grp_fu_132_p_ce(grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_ce)
);

FFT_IP_BUS_A_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUS_A_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUS_A_DATA_WIDTH ))
BUS_A_s_axi_U(
    .AWVALID(s_axi_BUS_A_AWVALID),
    .AWREADY(s_axi_BUS_A_AWREADY),
    .AWADDR(s_axi_BUS_A_AWADDR),
    .WVALID(s_axi_BUS_A_WVALID),
    .WREADY(s_axi_BUS_A_WREADY),
    .WDATA(s_axi_BUS_A_WDATA),
    .WSTRB(s_axi_BUS_A_WSTRB),
    .ARVALID(s_axi_BUS_A_ARVALID),
    .ARREADY(s_axi_BUS_A_ARREADY),
    .ARADDR(s_axi_BUS_A_ARADDR),
    .RVALID(s_axi_BUS_A_RVALID),
    .RREADY(s_axi_BUS_A_RREADY),
    .RDATA(s_axi_BUS_A_RDATA),
    .RRESP(s_axi_BUS_A_RRESP),
    .BVALID(s_axi_BUS_A_BVALID),
    .BREADY(s_axi_BUS_A_BREADY),
    .BRESP(s_axi_BUS_A_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

FFT_IP_faddfsub_32ns_32ns_32_10_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_10_full_dsp_1_U107(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_124_p0),
    .din1(grp_fu_124_p1),
    .opcode(grp_fu_124_opcode),
    .ce(grp_fu_124_ce),
    .dout(grp_fu_124_p2)
);

FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_7_max_dsp_1_U108(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_128_p0),
    .din1(grp_fu_128_p1),
    .ce(grp_fu_128_ce),
    .dout(grp_fu_128_p2)
);

FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_7_max_dsp_1_U109(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_132_p0),
    .din1(grp_fu_132_p1),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_IP_Pipeline_1_fu_86_ap_ready == 1'b1)) begin
            grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_ready == 1'b1)) begin
            grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_ready == 1'b1)) begin
            grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_transform_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_transform_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_transform_fu_100_ap_ready == 1'b1)) begin
            grp_transform_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_FFT_IP_Pipeline_1_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_transform_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f_M_value_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        f_M_value_1_address0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_1_address0 = grp_transform_fu_100_f_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_1_address0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_1_address0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_address0;
    end else begin
        f_M_value_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_M_value_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        f_M_value_1_ce0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_1_ce0 = grp_transform_fu_100_f_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_1_ce0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_1_ce0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_ce0;
    end else begin
        f_M_value_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_1_ce1 = grp_transform_fu_100_f_1_ce1;
    end else begin
        f_M_value_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f_M_value_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_1_d0 = grp_transform_fu_100_f_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_1_d0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_1_d0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_d0;
    end else begin
        f_M_value_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_M_value_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_1_we0 = grp_transform_fu_100_f_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_1_we0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_1_we0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_1_we0;
    end else begin
        f_M_value_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f_M_value_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        f_M_value_address0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_address0 = grp_transform_fu_100_f_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_address0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_address0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_address0;
    end else begin
        f_M_value_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_M_value_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        f_M_value_ce0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_f_M_value_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_ce0 = grp_transform_fu_100_f_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_ce0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_ce0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_ce0;
    end else begin
        f_M_value_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_ce1 = grp_transform_fu_100_f_0_ce1;
    end else begin
        f_M_value_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        f_M_value_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_d0 = grp_transform_fu_100_f_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_d0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_d0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_d0;
    end else begin
        f_M_value_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_M_value_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        f_M_value_we0 = grp_transform_fu_100_f_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        f_M_value_we0 = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_f_M_value_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        f_M_value_we0 = grp_FFT_IP_Pipeline_1_fu_86_f_M_value_we0;
    end else begin
        f_M_value_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_124_ce = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_124_ce = grp_transform_fu_100_grp_fu_124_p_ce;
    end else begin
        grp_fu_124_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_124_opcode = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_124_opcode = grp_transform_fu_100_grp_fu_124_p_opcode;
    end else begin
        grp_fu_124_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_124_p0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_124_p0 = grp_transform_fu_100_grp_fu_124_p_din0;
    end else begin
        grp_fu_124_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_124_p1 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_124_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_124_p1 = grp_transform_fu_100_grp_fu_124_p_din1;
    end else begin
        grp_fu_124_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_128_ce = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_128_ce = grp_transform_fu_100_grp_fu_128_p_ce;
    end else begin
        grp_fu_128_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_128_p0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_128_p0 = grp_transform_fu_100_grp_fu_128_p_din0;
    end else begin
        grp_fu_128_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_128_p1 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_128_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_128_p1 = grp_transform_fu_100_grp_fu_128_p_din1;
    end else begin
        grp_fu_128_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_132_ce = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_132_ce = grp_transform_fu_100_grp_fu_132_p_ce;
    end else begin
        grp_fu_132_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_132_p0 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_132_p0 = grp_transform_fu_100_grp_fu_132_p_din0;
    end else begin
        grp_fu_132_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_132_p1 = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_grp_fu_132_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_132_p1 = grp_transform_fu_100_grp_fu_132_p_din1;
    end else begin
        grp_fu_132_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_FFT_IP_Pipeline_1_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_transform_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ExtVolDataIn_Addr_A = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_Addr_A;

assign ExtVolDataIn_Clk_A = ap_clk;

assign ExtVolDataIn_Din_A = 32'd0;

assign ExtVolDataIn_EN_A = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ExtVolDataIn_EN_A;

assign ExtVolDataIn_Rst_A = ap_rst_n_inv;

assign ExtVolDataIn_WEN_A = 4'd0;

assign ExtVolDataOut_Addr_A = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Addr_A;

assign ExtVolDataOut_Clk_A = ap_clk;

assign ExtVolDataOut_Din_A = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_Din_A;

assign ExtVolDataOut_EN_A = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_EN_A;

assign ExtVolDataOut_Rst_A = ap_rst_n_inv;

assign ExtVolDataOut_WEN_A = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ExtVolDataOut_WEN_A;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_FFT_IP_Pipeline_1_fu_86_ap_start = grp_FFT_IP_Pipeline_1_fu_86_ap_start_reg;

assign grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start = grp_FFT_IP_Pipeline_VITIS_LOOP_112_3_fu_116_ap_start_reg;

assign grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start = grp_FFT_IP_Pipeline_VITIS_LOOP_97_1_fu_92_ap_start_reg;

assign grp_transform_fu_100_ap_start = grp_transform_fu_100_ap_start_reg;

endmodule //FFT_IP
