#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Apr 08 20:19:22 +0100 2025
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_lite_ipif_v3_0_4 axi_intc_v4_1_17 xil_defaultlib lib_cdc_v1_0_2 lib_pkg_v1_0_2 axi_timer_v2_0_29 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_27 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 proc_sys_reset_v5_0_13 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 axi_bram_ctrl_v4_1_7 blk_mem_gen_v8_4_5 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_1_15 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/802b/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_intc_0_0/sim/design_1_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_29 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/22b2/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_0/sim/design_1_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_250M_0/sim/design_1_rst_ps8_0_250M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_7 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/f80b/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_1/sim/design_1_axi_bram_ctrl_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_1/sim/design_1_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_1_0/sim/design_1_blk_mem_gen_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_15 $vhdlan_opts \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work floating_point_v7_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/22f8/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_BUS_A_s_axi.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_f_M_value_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_faddfsub_32ns_32ns_32_10_full_dsp_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_FFT_IP_Pipeline_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_FFT_IP_Pipeline_VITIS_LOOP_97_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_FFT_IP_Pipeline_VITIS_LOOP_112_3.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_fptrunc_64ns_32_3_no_dsp_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_fsqrt_32ns_32ns_32_28_no_dsp_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_13ns_32s_32_3_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_32s_32s_32_3_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_33ns_34ns_66_3_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_44s_44ns_87_3_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_52s_54ns_105_5_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mul_64s_64s_126_5_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_mux_42_32_1_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_Pipeline_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_Pipeline_2.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_Pipeline_3.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K0_V_ROM_1P_LUTRAM_1R.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K1_V_ROM_1P_LUTRAM_1R.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K2_V_ROM_1P_LUTRAM_1R.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K3_V_ROM_1P_LUTRAM_1R.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_sin_or_cos_double_s_fourth_order_double_sin_cos_K4_V_ROM_1P_LUTRAM_1R.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_srem_32ns_32ns_32_36_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_f2_M_value_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_4.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_5.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_VITIS_LOOP_44_1.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_VITIS_LOOP_47_2.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP_transform_Pipeline_VITIS_LOOP_63_2_VITIS_LOOP_65_3.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/verilog/FFT_IP.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/ip/FFT_IP_faddfsub_32ns_32ns_32_10_full_dsp_1_ip.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/ip/FFT_IP_fmul_32ns_32ns_32_7_max_dsp_1_ip.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/ip/FFT_IP_fptrunc_64ns_32_3_no_dsp_1_ip.v" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4228/hdl/ip/FFT_IP_fsqrt_32ns_32ns_32_28_no_dsp_1_ip.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_FFT_IP_1_0/sim/design_1_FFT_IP_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/src/floating_point_0/sim/floating_point_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/eace/hdl/AXI_peak_finder_final_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_1/ipshared/eace/src/fp_gt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/eace/src/peak_finder_fp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/eace/hdl/AXI_peak_finder_final_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/sim/design_1_AXI_peak_finder_final_0_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../FINAL.gen/sources_1/bd/design_1/ip/design_1_FFT_IP_1_0/drivers/FFT_IP_v1_0/src" +incdir+"E:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_3/sim/design_1_auto_ds_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_4/sim/design_1_auto_ds_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_5/sim/design_1_auto_ds_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_3/sim/design_1_auto_pc_3.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
