# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Robot/MastersSafeKeeping/FINAL/FINAL.srcs/sources_1/bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/design_1_AXI_peak_finder_final_0_0.xci
# IP: The module: 'design_1_AXI_peak_finder_final_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Robot/MastersSafeKeeping/FINAL/FINAL.gen/sources_1/bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/src/floating_point_0/floating_point_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: C:/Users/Robot/MastersSafeKeeping/FINAL/FINAL.srcs/sources_1/bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/design_1_AXI_peak_finder_final_0_0.xci
# IP: The module: 'design_1_AXI_peak_finder_final_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Robot/MastersSafeKeeping/FINAL/FINAL.gen/sources_1/bd/design_1/ip/design_1_AXI_peak_finder_final_0_0/src/floating_point_0/floating_point_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet
